export const FETCH_POSTS = 'FETCH_POSTS'
export const SET_POSTS_STATUS = 'SET_POSTS_STATUS'
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS'

export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
